### ISSUE TITLE
World Boss Stopped Working 

### ISSUE THREAD

**Issue by jeisonfura** [tmarenko/mff_auto#12]
`2020-11-22` 23:43:03,326 - world_bosses - INFO - World Boss: starting ULTIMATE battle.
2020-11-22 23:43:04,131 - queue_manager - DEBUG - Queue completed.
2020-11-22 23:47:45,329 - main - INFO - Acquire Heroic Quest rewards: False
2020-11-22 23:47:49,413 - game - DEBUG - Loading circle is on screen.
2020-11-22 23:47:58,654 - threading - ERROR - <class 'AttributeError'>
'NoneType' object has no attribute 'isEnabled'
  File "C:\Users\GAMEMAKER\Desktop\mff-auto-0.7.5\lib\gui\helper.py", line 51, in proxy_func
    return func(*args, **kwargs)
  File "C:\Users\GAMEMAKER\Desktop\mff-auto-0.7.5\lib\gui\widgets\main.py", line 221, in block_buttons
    buttons_to_block = [button for button in self.blockable_buttons if
  File "C:\Users\GAMEMAKER\Desktop\mff-auto-0.7.5\lib\gui\widgets\main.py", line 222, in <listcomp>
    button.isEnabled() and button != `caller_button]`

Also, this: 
`2020-11-23` 11:08:43,911 - world_bosses - DEBUG - World Boss ad was closed: False
2020-11-23 11:08:45,474 - world_bosses - INFO - World Boss: starting ULTIMATE battle.
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\GAMEMAKER\Desktop\mff-auto-0.7.5\python\App\Python\lib\site-packages\multiprocess\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\GAMEMAKER\Desktop\mff-auto-0.7.5\python\App\Python\lib\site-packages\multiprocess\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\GAMEMAKER\Desktop\mff-auto-0.7.5\lib\gui\helper.py", line 163, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\GAMEMAKER\Desktop\mff-auto-0.7.5\lib\gui\widgets\queue_item_editor.py", line 410, in do_missions
    return game_mode.do_missions(*args, **kwargs)
  File "C:\Users\GAMEMAKER\Desktop\mff-auto-0.7.5\lib\game\missions\world_bosses.py", line 61, in do_missions
    self.start_missions(mode=mode, difficulty=difficulty, boss=boss)
  File "C:\Users\GAMEMAKER\Desktop\mff-auto-0.7.5\lib\game\missions\world_bosses.py", line 118, in start_missions
    self.select_stage_level(level_num=difficulty)
  File "C:\Users\GAMEMAKER\Desktop\mff-auto-0.7.5\lib\game\missions\world_bosses.py", line 281, in select_stage_level
    diff = abs(level_num - self.stage_level)
  File "C:\Users\GAMEMAKER\Desktop\mff-auto-0.7.5\lib\game\missions\world_bosses.py", line 251, in stage_level
    stage_str = self.player.get_screen_text(ui_element=self.stage_ui)
  File "C:\Users\GAMEMAKER\Desktop\mff-auto-0.7.5\lib\players\android_emulator.py", line 228, in get_screen_text
    image = screen if screen is not None else self.get_screen_image(ui_element.rect)
AttributeError: 'NoneType' object has no attribute `'rect'`
``

**Comment by tmarenko** [comment]
> 2020-11-22 23:47:58,654 - threading - ERROR - <class 'AttributeError'>
> 'NoneType' object has no attribute 'isEnabled'

Fixed in b0eebd5932672ab490a8883206086cd38c57d4ab

> File "C:\Users\GAMEMAKER\Desktop\mff-auto-0.7.5\lib\players\android_emulator.py", line 228, in get_screen_text
> image = screen if screen is not None else self.get_screen_image(ui_element.rect)
> AttributeError: 'NoneType' object has no attribute 'rect'

Fixed in c68a0798350db63e5ebf91161dfe2f61148bd43b

**Comment by tmarenko** [comment]
Released in https://github.com/tmarenko/mff_auto/releases/tag/0.7.6
