### ISSUE TITLE
Not restarting game 

### ISSUE THREAD

**Issue by NuanKi** [tmarenko/mff_auto#46]
https://user-images.githubusercontent.com/80914838/135873614-baf284c4-e5e4-4432-b638-a572662192e0.mp4

when using the restart game button or when you do the shifters missions the game closes but does not reopen.
I delete game.json to configure it again and when configuring, it closes and opens the game, but then it continues with the problem where it does not open

**Comment by NuanKi** [comment]
https://user-images.githubusercontent.com/80914838/135874540-d497c596-1bd6-4b5a-aa22-e3b8e0a5815d.mp4

**Comment by tmarenko** [comment]
Can you upload video to youtube or similar video hosting? For some reason I can't view videos on github

**Comment by NuanKi** [comment]
sure

**Comment by NuanKi** [comment]
https://www.youtube.com/watch?v=a3zIslLmJZs

**Comment by tmarenko** [comment]
Seems it clicks right in the middle with default position: https://github.com/tmarenko/mff_auto/blob/master/lib/game/ui/elements/main_menu.py#L124

What's the value of `game_app_rect` in your `game.json` file?

**Comment by NuanKi** [comment]
"game_app_rect": [0.7099841521394612, 0.2994350282485876, 0.7099841521394612, 0.2994350282485876]}

**Comment by tmarenko** [comment]
Is there any errors in log files or inside console window? Usually value from `game_app_rect` is copied to `GAME_APP` UI:
https://github.com/tmarenko/mff_auto/blob/master/lib/gui/widgets/main.py#L243

**Comment by NuanKi** [comment]
2021-10-04 10:07:52,591 - INFO - updater - Loaded version: mff_auto=0.9.0, game=7.4.0, updater=1.1.0
2021-10-04 10:07:53,125 - INFO - updater - Current version 0.9.0 is up to date for Marvel Future Fight 7.4.0.
2021-10-04 10:07:54,018 - DEBUG - root - Creating 1 Tesseract API(s) with 'eng' language.
2021-10-04 10:07:54,225 - DEBUG - root - Creating 1 Tesseract API(s) with 'mff+eng' language.
2021-10-04 10:07:55,336 - DEBUG - root - -------- 7.0.1.0: found `Close App` shortcut at position 8
2021-10-04 10:07:55,337 - DEBUG - root - Initialized NoxPlayer object with name NuanKi version 7.0.1.0 and resolution (1280, 720); main window: (2, 32, 1282, 752), parent: (214, 136)
2021-10-04 10:07:55,340 - DEBUG - root - NuanKi 7.0.1.0: found `Close App` shortcut at position 8
2021-10-04 10:08:34,189 - INFO - root - --------: saved config file conf.ini. Need to restart emulator to apply changes.
2021-10-04 10:09:01,916 - DEBUG - main - Saving setting from first setup.
2021-10-04 10:09:01,950 - DEBUG - root - -------- 7.0.1.0: found `Close App` shortcut at position 8
2021-10-04 10:09:01,953 - DEBUG - root - Initialized NoxPlayer object with name NuanKi version 7.0.1.0 and resolution (1280, 720); main window: (2, 32, 1282, 752), parent: (214, 136)
2021-10-04 10:09:01,954 - DEBUG - root - -------- 7.0.1.0: found `Close App` shortcut at position 8
2021-10-04 10:09:02,711 - WARNING - main - Can't get to the main menu. Restarting the game just in case.
2021-10-04 10:09:02,714 - DEBUG - single_task_manager - Executing single task: RestartGameTask restart_game
2021-10-04 10:09:05,012 - DEBUG - game - Closing game.
2021-10-04 10:09:06,916 - DEBUG - game - Starting game.
2021-10-04 10:09:10,754 - DEBUG - single_task_manager - Task was forcibly stopped.
2021-10-04 10:09:10,772 - DEBUG - single_task_manager - Task completed.
2021-10-04 10:09:11,836 - DEBUG - single_task_manager - Executing single task: RestartGameTask restart_game
2021-10-04 10:09:13,491 - DEBUG - game - Closing game.
2021-10-04 10:09:15,627 - DEBUG - game - Starting game.
2021-10-04 10:11:23,553 - ERROR - game - Failed to start game
2021-10-04 10:11:23,735 - DEBUG - single_task_manager - Task completed.

**Comment by NuanKi** [comment]
no error appears until after a while in which the game does not open

**Comment by tmarenko** [comment]
What about other settings (example on screenshot)?
![image](https://user-images.githubusercontent.com/31345208/135878353-1aa57153-2c87-408a-8b63-6aea4395b719.png)

Do they load correctly and do they match values from `game.json` (timeline_team, mission_team, etc.)?

**Comment by NuanKi** [comment]
{"timeline_team": 2, "mission_team": 4, "acquire_heroic_quest_rewards": true, "handle_network_errors": false
![capture_20211004102440641](https://user-images.githubusercontent.com/80914838/135879094-29c4ebdd-9a25-49e7-b3c5-9f6ab3d81488.png)
,

**Comment by NuanKi** [comment]
everything else seems to load correctly

**Comment by tmarenko** [comment]
I was able to reproduce this issue, looking into it. Seems overriding UI elements isn't synchronized between processes (tasks)

**Comment by NuanKi** [comment]
the problem keeps happening to me even though I re-downloaded and configured everything

**Comment by tmarenko** [comment]
> I was able to reproduce this issue, looking into it. 

The temporary fix is to override default value inside `settings/ui_override.py` file. Just add this line at the end:
`GAME_APP.button_rect = Rect(0.7099841521394612, 0.2994350282485876, 0.7099841521394612, 0.2994350282485876)`

**Comment by NuanKi** [comment]
k, thanks for everything

**Comment by tmarenko** [comment]
Fixed in https://github.com/tmarenko/mff_auto/commit/432cb9c8cbadcbbb0a7d9b9f83ffcca64a6e1210

**Comment by NuanKi** [comment]
Error code in shifter missions


2021-10-05 19:05:55,052 - DEBUG - game - Closing game.
2021-10-05 19:05:57,054 - DEBUG - game - Starting game.
2021-10-05 19:06:54,938 - DEBUG - game - Game started successfully.
2021-10-05 19:06:57,598 - ERROR - root - 'TWISTED WORLD'
Traceback (most recent call last):
  File "C:\Users\emman\Desktop\mff_auto-0.9.0-build\lib\gui\helper.py", line 226, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\emman\Desktop\mff_auto-0.9.0-build\lib\gui\widgets\queue_items\general.py", line 164, in do_missions
    return game_mode.do_missions(*args, **kwargs)
  File "C:\Users\emman\Desktop\mff_auto-0.9.0-build\lib\game\missions\epic_quest.py", line 61, in do_missions
    self.start_missions(farm_shifter_bios=farm_shifter_bios)
  File "C:\Users\emman\Desktop\mff_auto-0.9.0-build\lib\game\missions\epic_quest.py", line 120, in start_missions
    stage_1_num = self.start_stage(self.stage_1_ui, stage_1_num, farm_shifter_bios=farm_shifter_bios)
  File "C:\Users\emman\Desktop\mff_auto-0.9.0-build\lib\game\missions\epic_quest.py", line 39, in start_stage
    self.game.select_mode(self.mode_name)
  File "C:\Users\emman\Desktop\mff_auto-0.9.0-build\lib\game\game.py", line 340, in select_mode
    mode = self._modes[name]
  File "<string>", line 2, in __getitem__
  File "C:\Users\emman\Desktop\mff_auto-0.9.0-build\python\App\Python\lib\site-packages\multiprocess\managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 'TWISTED WORLD'

**Comment by tmarenko** [comment]
> KeyError: 'TWISTED WORLD'

Forgot that `restart_game` now clears game modes. This should fix it: https://github.com/tmarenko/mff_auto/commit/b91f3a7f01d678a660a282583624582a33fdb0d4

**Comment by tmarenko** [comment]
Released in https://github.com/tmarenko/mff_auto/releases/tag/0.9.1
